parameter_dict = {'initial_flocks': [[[5., 5.], 1., 50],
                                     [[1.2, 7.3], 3, 65],
                                     [[8.2, 5.3], 5, 150]],
                  'num_points': 150,
                  'box_size': 15,
                  'w_amp': 0.0,
                  'w0': 0.0,
                  'speed': 1.0,
                  'C': 3.5,
                  'nu': 1.,
                  'max_dist': 0.5,
                  'max_num': 200}
